name: YeePortals
version: 0.1
main: me.nachtok0.yeeportals.YeePortals
author: nachtok0
api-version: 1.13
description: Simple and lightweight portal plugin

commands:
  portal:

permissions:
  portal.admin:
    default: op